### PR TITLE
Gallery

### PR DESCRIPTION
**Pull request by KevinRoig**

### CODE REVIEW

**Review by AurelieFqt — DISMISSED** [review]
ok

**Review by AurelieFqt — DISMISSED** [review]
ok

**Review by RomainClair — CHANGES_REQUESTED** [review]
The controller_name twig parameters are probably useless now, you should remove them

**Review by AurelieFqt — DISMISSED** [review]

**Review by RomainClair — CHANGES_REQUESTED** [review]
Your HTML seems invalid, you have a `<li>` ouside `<ul>`
And gallery in french is galerie (only one l)

**Review by AurelieFqt — DISMISSED** [review]

**Review by AurelieFqt — DISMISSED** [review]

**Review by AshBll — DISMISSED** [review]

**Review by rickifox — DISMISSED** [review]

**Comment by KevinRoig** [comment]
Too many issues on this branch, i delete it and i went back before troubles on "save" branch.

**Pull request closed without merging**
